name: Github Actions for PHP with PHPUnit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer update

      - name: Run test suite
        run: composer run-script testdox